version = 0.1
[default.deploy.parameters]
stack_name = "dashboard-app"
resolve_s3 = true
s3_prefix = "dashboard-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ConnectionMappingTableName=\"RTBDashConnections\" TrackingTableName=\"RTBDashTracking\""
image_repositories = []